name: Release Go Code
on:
  create:
    tags:
      - v*

jobs:
  release: # any name
    name: Release on Github
    runs-on: ubuntu-latest
    steps:
      - name: Checkout codes
        uses: actions/checkout@v2

      - name: Validate Go codes
        uses: goreleaser/goreleaser-action@v2.6.1
        with:
          args: check
      - name: Release the Go code
        uses: goreleaser/goreleaser-action@v2.6.1
        with:
          args: release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
