name: CI setup for go # name the workflow
on: # on event keyword
  push: # the event is push
    branches: [main] # on main branch

jobs: # job to execute
  my_job:
    name: My job
    runs-on: ubuntu-latest # specify OS in VM
    steps:
    - name: Print a greeting
      run: |
        ls
        echo "Hello World!"

    - name: Setup Go environment
      uses: actions/setup-go@v2.1.3
      with:
        # The Go version to download (if necessary) and use. Supports semver spec and ranges.
        go-version: 1.16.5 # optional
        
    - name: Show GO version # verify that GO is installed
      run: go version # show go version
      
    - name: Checkout our codes # bring repo code to VM
      uses: actions/checkout@v2.3.4
      
    - name: Check file system # check VM has the files
      run: |
        ls
        cat calc.go
