name: CI setup for go # name the workflow
on: # on event keyword
  push: # the event is push
    branches: [main] # on main branch

jobs: # job to execute
  my_job:
    name: My job
    runs-on: ubuntu-latest # specify OS in VM
    steps:
    - name: Print a greeting
      run: |
        ls
        echo "Hello World!"

    - name: Setup Go environment
      uses: actions/setup-go@v2.1.3
      with:
        # The Go version to download (if necessary) and use. Supports semver spec and ranges.
        go-version: 1.16.5 # optional
        
    - name: Show GO version # verify that GO is installed
      run: go version # show go version
      
    - name: Checkout our codes # bring repo code to VM
      uses: actions/checkout@v2.3.4
      
    - name: Check file system # check VM has the files
      run: |
        ls
        cat calc.go
        
    - name: Checkout private repo remotely
      uses: actions/checkout@v2.3.4
      with:
        repository: lowkh2/GoSchoolRemoteExample # the hidden repo
        path: virtualRepoFolder # folder to save in the VM env
        token: ${{ secrets.GO_SECRET }}
    
    - name: Show hidden files
      run: |
        cd virtualRepoFolder
        ls
        cat myText.txt
        cd ..
    
    - name: Install dependencies for Go
      run: |
        go get github.com/franela/goblin
        go get github.com/tebeka/go2xunit
        go test -v
